package com.example.codise.utils

import androidx.compose.runtime.compositionLocalOf
import com.example.codise.data.IdiomaApp

data class TextosApp(
    val nombreApp: String,
    // Navegación
    val inicio: String,
    val circuitos: String,
    val eventos: String,
    val mural: String,
    val perfil: String,
    val regresar: String,
    val verMas: String,
    val reintentar: String,
    val cancelar: String,
    val guardar: String,
    val cerrar: String,
    val entendido: String,
    val cargando: String,
    // Pantalla Principal
    val nicaragua: String,
    val seleccionarCiudad: String,
    val errorCargaCiudades: String,
    val descripcion: String,
    // Asistente
    val asistenteTitulo: String,
    val asistenteMensaje: String,
    // Perfil
    val cambiarFoto: String,
    val correoElectronico: String,
    val telefono: String,
    val nombreUsuario: String,
    val noRegistrado: String,
    val cerrarSesion: String,
    val idioma: String,
    val seleccionarIdioma: String,
    val rolStaff: String,
    val rolProtagonista: String,
    val rolTurista: String,
    val perfilActualizado: String,
    val editarPerfil: String,
    val misEmpresas: String,
    val registrarEmpresa: String,
    val registrarNuevaEmpresa: String,
    val empresaRegistradaExito: String,
    val empresaRegistradaSub: String,
    // Eventos
    val sinEventosProximos: String,
    val vuelveMasTardeEventos: String,
    val asistir: String,
    val noAsistire: String,
    val llegar: String,
    val gratis: String,
    val organizadoPor: String,
    val cupoMaximo: String,
    val personas: String,
    val subirEvento: String,
    val nuevoEvento: String,
    val eventoSubidoExito: String,
    val filtroTodos: String,
    val filtroOficiales: String,
    val filtroEnMural: String,
    val filtroMisAsistencias: String,
    // Circuitos y Puntos
    val circuitosTuristicos: String,
    val puntosDeInteres: String,
    val datosHistoricos: String,
    val galeriaMultimedia: String,
    val puntosDelRecorrido: String,
    val verificado: String,
    val visitado: String,
    val yaLoVisite: String,
    val comoLlegar: String,
    val compartir: String,
    val epoca: String,
    val distancia: String,
    val duracion: String,
    val dificultad: String,
    val sinCircuitos: String,
    val sinPuntosInteres: String,
    // Publicaciones / Mural
    val publicaciones: String,
    val sinPublicaciones: String,
    val seElPrimeroPublicar: String,
    val nuevaPublicacion: String,
    val meGusta: String,
    val comentarios: String,
    val escribeComentario: String,
    val publicar: String,
    val publicarExperiencia: String,
    // Inicio Sesión / Registro
    val iniciarSesion: String,
    val crearCuenta: String,
    val nombre: String,
    val apellido: String,
    val contrasena: String,
    val correo: String,
    val noTienesCuenta: String,
    val yaTienesCuenta: String,
    val continuarConGoogle: String,
    val soyTurista: String,
    val soyProtagonista: String,
    val seleccionaSoloUno: String
)

val CadenasEspanol = TextosApp(
    nombreApp = "Codice路",
    inicio = "Inicio",
    circuitos = "Circuitos",
    eventos = "Eventos",
    mural = "Mural",
    perfil = "Perfil",
    regresar = "Regresar",
    verMas = "Ver más",
    reintentar = "Reintentar",
    cancelar = "Cancelar",
    guardar = "Guardar Cambios",
    cerrar = "Cerrar",
    entendido = "Entendido",
    cargando = "Cargando...",
    nicaragua = "NICARAGUA",
    seleccionarCiudad = "Selecciona una ciudad",
    errorCargaCiudades = "Error al cargar ciudades",
    descripcion = "Descripción",
    asistenteTitulo = "Asistente Guardabarranco",
    asistenteMensaje = "¡Hola! Soy tu asistente Guardabarranco. Pronto podré ayudarte con recomendaciones turísticas personalizadas, rutas y eventos en Nicaragua.",
    cambiarFoto = "Toca para cambiar foto",
    correoElectronico = "Correo Electrónico",
    telefono = "Teléfono",
    nombreUsuario = "Nombre de Usuario",
    noRegistrado = "No registrado",
    cerrarSesion = "Cerrar Sesión",
    idioma = "Idioma",
    seleccionarIdioma = "Seleccionar Idioma",
    rolStaff = "Staff",
    rolProtagonista = "Protagonista",
    rolTurista = "Turista",
    perfilActualizado = "¡Perfil actualizado con éxito!",
    editarPerfil = "Editar Información de Perfil",
    misEmpresas = "Mis Empresas / Emprendimientos",
    registrarEmpresa = "Registrar Empresa",
    registrarNuevaEmpresa = "Registrar Nueva Empresa",
    empresaRegistradaExito = "¡Empresa registrada con éxito!",
    empresaRegistradaSub = "Ahora eres Protagonista. Ya puedes crear eventos y publicaciones.",
    sinEventosProximos = "No hay eventos próximos",
    vuelveMasTardeEventos = "Vuelve más tarde para ver nuevas actividades",
    asistir = "Asistir",
    noAsistire = "Ya no asistiré",
    llegar = "Llegar",
    gratis = "GRATIS",
    organizadoPor = "Organizado por",
    cupoMaximo = "Cupo Máximo",
    personas = "personas",
    subirEvento = "Subir Evento",
    nuevoEvento = "Nuevo Evento",
    eventoSubidoExito = "¡Evento creado con éxito!",
    filtroTodos = "Todos",
    filtroOficiales = "Oficiales",
    filtroEnMural = "En Mural",
    filtroMisAsistencias = "Mis Asistencias",
    circuitosTuristicos = "Circuitos Turísticos",
    puntosDeInteres = "Puntos de Interés",
    datosHistoricos = "Datos Históricos",
    galeriaMultimedia = "Galería Multimedia",
    puntosDelRecorrido = "Puntos del Recorrido",
    verificado = "Verificado",
    visitado = "Visitado",
    yaLoVisite = "Ya lo visité",
    comoLlegar = "Cómo llegar",
    compartir = "Compartir",
    epoca = "Época",
    distancia = "Distancia",
    duracion = "Duración",
    dificultad = "Dificultad",
    sinCircuitos = "No hay circuitos disponibles.",
    sinPuntosInteres = "No hay puntos de interés disponibles.",
    publicaciones = "Publicaciones",
    sinPublicaciones = "Aún no hay publicaciones",
    seElPrimeroPublicar = "¡Sé el primero en compartir tu experiencia!",
    nuevaPublicacion = "Nueva Publicación",
    meGusta = "Me gusta",
    comentarios = "Comentarios",
    escribeComentario = "Escribe un comentario...",
    publicar = "Publicar",
    publicarExperiencia = "Publicar Experiencia",
    iniciarSesion = "Iniciar Sesión",
    crearCuenta = "Crear Cuenta",
    nombre = "Nombre",
    apellido = "Apellido",
    contrasena = "Contraseña",
    correo = "Correo Electrónico",
    noTienesCuenta = "¿No tienes cuenta? Regístrate",
    yaTienesCuenta = "¿Ya tienes cuenta? Inicia Sesión",
    continuarConGoogle = "Continuar con Google",
    soyTurista = "Soy Turista",
    soyProtagonista = "Soy Protagonista / Emprendedor",
    seleccionaSoloUno = "Selecciona solo una opción"
)

val CadenasIngles = TextosApp(
    nombreApp = "Codice路",
    inicio = "Home",
    circuitos = "Circuits",
    eventos = "Events",
    mural = "Feed",
    perfil = "Profile",
    regresar = "Back",
    verMas = "See more",
    reintentar = "Retry",
    cancelar = "Cancel",
    guardar = "Save Changes",
    cerrar = "Close",
    entendido = "Got it",
    cargando = "Loading...",
    nicaragua = "NICARAGUA",
    seleccionarCiudad = "Select a city",
    errorCargaCiudades = "Failed to load cities",
    descripcion = "Description",
    asistenteTitulo = "Guardabarranco Assistant",
    asistenteMensaje = "Hello! I am your Guardabarranco assistant. Soon I will be able to help you with personalized tourist recommendations, routes, and events across Nicaragua.",
    cambiarFoto = "Tap to change photo",
    correoElectronico = "Email Address",
    telefono = "Phone",
    nombreUsuario = "Username",
    noRegistrado = "Not registered",
    cerrarSesion = "Log Out",
    idioma = "Language",
    seleccionarIdioma = "Select Language",
    rolStaff = "Staff",
    rolProtagonista = "Organizer",
    rolTurista = "Tourist",
    perfilActualizado = "Profile updated successfully!",
    editarPerfil = "Edit Profile Information",
    misEmpresas = "My Businesses / Ventures",
    registrarEmpresa = "Register Business",
    registrarNuevaEmpresa = "Register New Business",
    empresaRegistradaExito = "Business registered successfully!",
    empresaRegistradaSub = "You are now an Organizer. You can now create events and publications.",
    sinEventosProximos = "No upcoming events",
    vuelveMasTardeEventos = "Check back later for new activities",
    asistir = "Attend",
    noAsistire = "Cancel attendance",
    llegar = "Directions",
    gratis = "FREE",
    organizadoPor = "Organized by",
    cupoMaximo = "Max Capacity",
    personas = "people",
    subirEvento = "Create Event",
    nuevoEvento = "New Event",
    eventoSubidoExito = "Event created successfully!",
    filtroTodos = "All",
    filtroOficiales = "Official",
    filtroEnMural = "On Feed",
    filtroMisAsistencias = "Attending",
    circuitosTuristicos = "Touristic Circuits",
    puntosDeInteres = "Points of Interest",
    datosHistoricos = "Historical Facts",
    galeriaMultimedia = "Multimedia Gallery",
    puntosDelRecorrido = "Circuit Stops",
    verificado = "Verified",
    visitado = "Visited",
    yaLoVisite = "I visited",
    comoLlegar = "Directions",
    compartir = "Share",
    epoca = "Era",
    distancia = "Distance",
    duracion = "Duration",
    dificultad = "Difficulty",
    sinCircuitos = "No circuits available.",
    sinPuntosInteres = "No points of interest available.",
    publicaciones = "Publications",
    sinPublicaciones = "No publications yet",
    seElPrimeroPublicar = "Be the first to share your experience!",
    nuevaPublicacion = "New Post",
    meGusta = "Like",
    comentarios = "Comments",
    escribeComentario = "Write a comment...",
    publicar = "Post",
    publicarExperiencia = "Post Experience",
    iniciarSesion = "Log In",
    crearCuenta = "Create Account",
    nombre = "First Name",
    apellido = "Last Name",
    contrasena = "Password",
    correo = "Email Address",
    noTienesCuenta = "Don't have an account? Sign Up",
    yaTienesCuenta = "Already have an account? Log In",
    continuarConGoogle = "Continue with Google",
    soyTurista = "I am a Tourist",
    soyProtagonista = "I am an Organizer / Entrepreneur",
    seleccionaSoloUno = "Please select only one option"
)

val CadenasChino = TextosApp(
    nombreApp = "Codice路",
    inicio = "首页",
    circuitos = "路线",
    eventos = "活动",
    mural = "动态",
    perfil = "个人",
    regresar = "返回",
    verMas = "查看更多",
    reintentar = "重试",
    cancelar = "取消",
    guardar = "保存修改",
    cerrar = "关闭",
    entendido = "知道了",
    cargando = "加载中...",
    nicaragua = "尼加拉瓜",
    seleccionarCiudad = "选择城市",
    errorCargaCiudades = "加载城市失败",
    descripcion = "简介",
    asistenteTitulo = "绿眉翠鴗助手",
    asistenteMensaje = "您好！我是您的绿眉翠鴗助手。我将很快能为您在尼加拉瓜提供个性化旅游推荐、路线和活动资讯。",
    cambiarFoto = "点击更换头像",
    correoElectronico = "电子邮件",
    telefono = "电话号码",
    nombreUsuario = "用户名",
    noRegistrado = "未登记",
    cerrarSesion = "退出登录",
    idioma = "语言 / Language",
    seleccionarIdioma = "选择语言",
    rolStaff = "管理员",
    rolProtagonista = "组织者 / 创业者",
    rolTurista = "游客",
    perfilActualizado = "个人资料更新成功！",
    editarPerfil = "编辑个人资料",
    misEmpresas = "我的企业 / 创业项目",
    registrarEmpresa = "注册企业",
    registrarNuevaEmpresa = "注册新企业",
    empresaRegistradaExito = "企业注册成功！",
    empresaRegistradaSub = "您现在已成为组织者，可以创建活动并发布动态。",
    sinEventosProximos = "暂无即将举行的活动",
    vuelveMasTardeEventos = "请稍后再来查看新活动",
    asistir = "参加",
    noAsistire = "取消参加",
    llegar = "导航",
    gratis = "免费",
    organizadoPor = "主办方",
    cupoMaximo = "人数上限",
    personas = "人",
    subirEvento = "创建活动",
    nuevoEvento = "新建活动",
    eventoSubidoExito = "活动创建成功！",
    filtroTodos = "全部",
    filtroOficiales = "官方",
    filtroEnMural = "动态墙",
    filtroMisAsistencias = "我参加的",
    circuitosTuristicos = "旅游路线",
    puntosDeInteres = "景点推荐",
    datosHistoricos = "历史故事",
    galeriaMultimedia = "多媒体图库",
    puntosDelRecorrido = "游览景点",
    verificado = "已核验",
    visitado = "已打卡",
    yaLoVisite = "打卡此地",
    comoLlegar = "导航路线",
    compartir = "分享",
    epoca = "年代",
    distancia = "距离",
    duracion = "预计耗时",
    dificultad = "难度",
    sinCircuitos = "暂无可用路线。",
    sinPuntosInteres = "暂无景点信息。",
    publicaciones = "动态社区",
    sinPublicaciones = "暂无动态",
    seElPrimeroPublicar = "成为第一个分享旅程体验的人吧！",
    nuevaPublicacion = "发布动态",
    meGusta = "点赞",
    comentarios = "评论",
    escribeComentario = "写下您的评论...",
    publicar = "发布",
    publicarExperiencia = "分享旅程",
    iniciarSesion = "登录",
    crearCuenta = "创建账号",
    nombre = "名",
    apellido = "姓",
    contrasena = "密码",
    correo = "电子邮件",
    noTienesCuenta = "还没有账号？立即注册",
    yaTienesCuenta = "已有账号？立即登录",
    continuarConGoogle = "使用 Google 继续",
    soyTurista = "我是游客",
    soyProtagonista = "我是创业者 / 主办方",
    seleccionaSoloUno = "请仅选择一项"
)

object CadenasIdiomas {
    fun obtener(idioma: IdiomaApp): TextosApp {
        return when (idioma) {
            IdiomaApp.ESPANOL -> CadenasEspanol
            IdiomaApp.INGLES -> CadenasIngles
            IdiomaApp.CHINO -> CadenasChino
        }
    }
}

val LocalCadenas = compositionLocalOf { CadenasEspanol }
